In [1]:
import numpy as np

In [ ]:
arr1 = np.arange(1,5).reshape(2,2)
m = np.matrix(arr1)
ndarray_T = arr1.T
matrix_T = m.T
print(f'ndarray transpose :\n {ndarray_T}')
print(f'matrix transpose :\n {matrix_T}')

ndarray transpose :
 [[1 3]
 [2 4]]
matrix transpose :
 [[1 3]
 [2 4]]


In [ ]:
# Linear Algebra function from linalg module
# numpy.linalg contains functions to perform linear algebra operations
#  inv()          ==> to find inverse of a matrix
#  matrix_power() ==> to find power of a matrix like A^n
#  det            ==> to find the determinant of a matrix
#  solve()        ==> to solve linear algebra equations

In [ ]:
arr1 = np.arange(1,).reshape(2,2)
arr1_inv = np.linalg.inv(arr1)
print(f"Original Matrix :: \n {arr1}")
print(f"Inverse of the Matrix :: \n {arr1_inv}")

Original Matrix :: 
 [[1 2]
 [3 4]]
Inverse of the Matrix :: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
arr1 = np.arange(1,5).reshape(2,2)
arr1_inv = np.linalg.inv(arr1)
dot_produt = np.dot(arr1,arr1_inv)
i = np.eye(2) # Identity matrix for the shape 2 ==> 2-D Arrray
print(f"Original Matrix :: \n {arr1}")
print(f"Inverse of the Matrix :: \n {arr1_inv}")
print(f"Dot product of Matrix and Inverse of Matrix :: \n {dot_produt}")
print(f"Identity Matrix(2-D array using eye() function):: \n {i}")

Original Matrix :: 
 [[1 2]
 [3 4]]
Inverse of the Matrix :: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Dot product of Matrix and Inverse of Matrix :: 
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
Identity Matrix(2-D array using eye() function):: 
 [[1. 0.]
 [0. 1.]]


In [ ]:
#allclose() function
arr1 = np.arange(1,5).reshape(2,2)
arr1_inv = np.linalg.inv(arr1)
print(arr1)
print(arr1_inv)
dot_produt = np.dot(arr1,arr1_inv)
print(dot_produt)
print(np.eye(2))
np.allclose(dot_produt,np.eye(2))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
[[1. 0.]
 [0. 1.]]


True

In [ ]:
# x+2y = 4
# 2x+5y= 9
coef = np.array([[1,2],[2,5]])
dep = np.array([4,9])
result = np.linalg.solve(coef,dep)
print(f"Coefficient Matrix : \n {coef}")
print(f"Dependent Matrix : \n {dep}")
print(f"Solution array : {result}")
print(f"Type of result : {type(result)}")

Coefficient Matrix : 
 [[1 2]
 [2 5]]
Dependent Matrix : 
 [4 9]
Solution array : [2. 1.]
Type of result : <class 'numpy.ndarray'>


In [ ]:
# 2x+3y-2z = 3
# x-2y+z = 3
# 2x-3y+z = -4
coef = np.array([[-4,7,-2],[1,-2,1],[2,-3,1]])
dep = np.array([2,3,-4])
result = np.linalg.solve(coef,dep)
print(f"Coefficient Matrix : \n {coef}")
print(f"Dependent Matrix : \n {dep}")
print(f"Solution array : {result}")

Coefficient Matrix : 
 [[-4  7 -2]
 [ 1 -2  1]
 [ 2 -3  1]]
Dependent Matrix : 
 [ 2  3 -4]
Solution array : [-13.  -6.   4.]


In [ ]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(4,0,-1).reshape(2,2)
print(f"array arr1 : \n {arr1}")
print(f"array arr2 : \n {arr2}")
print("Element level multiplication ")

ele_multiplication = arr1*arr2
print(f"array  : \n {ele_multiplication}")

dot_prod = np.dot(arr1,arr2)
print(f"array  : \n {dot_prod}")

array arr1 : 
 [[1 2]
 [3 4]]
array arr2 : 
 [[4 3]
 [2 1]]
Element level multiplication 
array  : 
 [[4 6]
 [6 4]]
array  : 
 [[ 8  5]
 [20 13]]


In [ ]:

mat1 = np.matrix(arr1)
mat2 = np.matrix(arr2)

# print(type(arr1))
# print(type(mat1))

mat1*mat2

matrix([[ 8,  5],
        [20, 13]])

In [ ]:
arr1 = np.array([70,20,60,10,50,40,30])
arr2 = np.sort(arr1)
print(f" arr1 : \n{arr1}")
print(f" arr2 : \n{arr2}")

 arr1 : 
[70 20 60 10 50 40 30]
 arr2 : 
[10 20 30 40 50 60 70]


In [ ]:
arr1 = np.array([70,20,60,10,50,40,30])
-arr1


array([-70, -20, -60, -10, -50, -40, -30])

In [ ]:
arr1 = np.arange(1,25).reshape(2,3,4)
# arr2 = np.dsplit(arr1,2) # 3 section
arr2 = np.dsplit(arr1,[2,4]) # 3 section
print(f"arr1 : \n{arr1}")
print(f"arr2 : \n{arr2}")

arr1 : 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
arr2 : 
[array([[[ 1,  2],
        [ 5,  6],
        [ 9, 10]],

       [[13, 14],
        [17, 18],
        [21, 22]]]), array([[[ 3,  4],
        [ 7,  8],
        [11, 12]],

       [[15, 16],
        [19, 20],
        [23, 24]]]), array([], shape=(2, 3, 0), dtype=int64)]


In [ ]:
arr1 = np.arange(1,44)
arr2 = np.array_split(arr1,6) # 3 section
print(f"arr1 : \n{arr1}")
print(f"arr2 : \n{arr2}")

arr1 : 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]
arr2 : 
[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20, 21, 22]), array([23, 24, 25, 26, 27, 28, 29]), array([30, 31, 32, 33, 34, 35, 36]), array([37, 38, 39, 40, 41, 42, 43])]


In [ ]:
arr1 = np.arange(1,65).reshape(4,4,4)
# arr2 = np.split(arr1,2) # 3 section
# arr2 = np.split(arr1,[2,4],axis=1) # 3 section
# print(f"arr1 : \n{arr1}")
# print(f"arr2 : \n{arr2}")

arr1 : 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]
arr2 : 
[array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]]), array([[[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]]])]


In [ ]:
# arr1 = np.arange(1,31).reshape(6,5)
arr2 = np.split(arr1,2,axis=0) # 3 section
# arr2 = np.split(arr1,2,axis=1) # 3 section
print(f"arr1 : \n{arr1}")
print(f"arr2 : \n{arr2}")

arr1 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
arr2 : 
[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])]


In [ ]:
arr1 = np.arange(0,5)
arr2 = np.split(arr1,3) # 3 section
print(f"arr1 : {arr1}")
print(f"type of arr2 : {type(arr2)}")
print(f"arr2 : {arr2}")

In [ ]:
arr1 = np.arange(0,5)
arr2 = np.split(arr1,[2,4,6,8])
print(f"arr1 : {arr1}")
print(f"type of arr2 : {type(arr2)}")
print(f"arr2 : {arr2}")

arr1 : [0 1 2 3 4]
type of arr2 : <class 'list'>
arr2 : [array([0, 1]), array([2, 3]), array([4]), array([], dtype=int64), array([], dtype=int64)]


In [ ]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(11,17).reshape(2,3)
print(f" arr1 \n {arr1}")
print(f" arr2 \n {arr2}")
arr3 = np.stack((arr1,arr2))
arr4 = np.stack((arr1,arr2),axis=1)
arr5 = np.stack((arr1,arr2),axis=2)
# print(f" shape {arr1.shape}")
# print(f" shape {arr2.shape}")
print(f" shape3  {arr3.shape}")
print(f" shape4  {arr4.shape}")
print(f" shape5  {arr5.shape}")

print(f" arr3 \n {arr3}")
print(f" arr4 \n {arr4}")
print(f" arr5 \n {arr5}")

 arr1 
 [[1 2 3]
 [4 5 6]]
 arr2 
 [[11 12 13]
 [14 15 16]]
 shape3  (2, 2, 3)
 shape4  (2, 2, 3)
 shape5  (2, 3, 2)
 arr3 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
 arr4 
 [[[ 1  2  3]
  [11 12 13]]

 [[ 4  5  6]
  [14 15 16]]]
 arr5 
 [[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]]


In [ ]:
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
arr3 = np.stack((arr1,arr2))
arr4 = np.stack((arr1,arr2),axis=1)
print(f" shape {arr1.shape}")
print(f" shape {arr2.shape}")
print(f" shape {arr3.shape}")
print(f" shape {arr4.shape}")

print(f" arr3 \n {arr3}")
print(f" arr4 \n {arr4}")


 shape (3,)
 shape (3,)
 shape (2, 3)
 shape (3, 2)
 arr3 
 [[10 20 30]
 [40 50 60]]
 arr4 
 [[10 40]
 [20 50]
 [30 60]]


In [ ]:
arr1 = np.arange(1,13).reshape(2,3,2)
arr2 = np.arange(11,29).reshape(2,3,3)

print(f"Array 1  \n {arr1}")
print(f"Array 2  \n {arr2}")

# # # Vertical Concatenation
# vcon = np.concatenate((arr1,arr2))
# print(f"Vertical Concatenation  \n {vcon}")

# # Horizontal Concateation
hcon = np.concatenate((arr1,arr2),axis=None)
print(f"Horizontal Concatenation  \n {hcon}")

# # # flatten and then concatenation
# flat = np.concatenate((arr1,arr2),axis=None)
# print(f"Flat Concatenation  \n {flat}")


Array 1  
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Array 2  
 [[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]]
Horizontal Concatenation  
 [ 1  2  3  4  5  6  7  8  9 10 11 12 11 12 13 14 15 16 17 18 19 20 21 22
 23 24 25 26 27 28]


In [ ]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(11,26).reshape(5,3)

print(f"Array 1  \n {arr1}")
print(f"Array 2  \n {arr2}")

# # # Vertical Concatenation
vcon = np.concatenate((arr1,arr2))
print(f"Vertical Concatenation  \n {vcon}")

# # # Horizontal Concateation
hcon = np.concatenate((arr1,arr2),axis=1)
print(f"Horizontal Concatenation  \n {hcon}")

# # # flatten and then concatenation
# flat = np.concatenate((arr1,arr2),axis=None)
# print(f"Flat Concatenation  \n {flat}")


Array 1  
 [[1 2 3]
 [4 5 6]]
Array 2  
 [[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]
 [23 24 25]]
Vertical Concatenation  
 [[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]
 [23 24 25]]


ValueError: ignored

In [38]:
arr1 =  np.arange(1,25).reshape(2,3,4)
arr1_tran = np.transpose(arr1)
a_swap1= np.swapaxes(arr1,2,0)
a_swap2= np.swapaxes(arr1,1,2)
print(f"Original Array  \n {arr1}")
print(f"Transpose Array 1  \n {arr1_tran}")
print(f"Swapped Array 1  \n {a_swap1}")
print(f"Swapped Array 2  \n {a_swap2}")

Original Array  
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Transpose Array 1  
 [[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
Swapped Array 1  
 [[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
Swapped Array 2  
 [[[ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]
  [ 4  8 12]]

 [[13 17 21]
  [14 18 22]
  [15 19 23]
  [16 20 24]]]


In [ ]:
arr1 = np.arange(1,7).reshape(3,2)
a_swap1= np.swapaxes(arr1,0,1)
a_swap2= np.swapaxes(arr1,1,0)
print(f"Original Array : \n {a}")
print(f"Swapped Array 1 : \n {a_swap1}")
print(f"Swapped Array 2 : \n {a_swap2}")
# print(f"Original Array shape : {a.shape}")
# print(f"Swapped Array shape: {aswap.shape}")

Original Array : 
 [[1 2]
 [3 4]
 [5 6]]
Swapped Array 1 : 
 [[1 3 5]
 [2 4 6]]
Swapped Array 2 : 
 [[1 3 5]
 [2 4 6]]


In [ ]:
arr1 = np.arange(24).reshape(2,3,4)
arr2 = arr1.ravel()
print(f"arr1 :\n {arr1}")
print(f"arr2 :\n {arr2}")

arr1 :
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
arr2 :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:

arr1 = np.arange(1,9).reshape(2,4)
arr1Trans = np.transpose(arr1)
print(f"arr1 : \n {arr1}")
print(f"arr1Trans : \n {arr1Trans}")

arr1 : 
 [[1 2 3 4]
 [5 6 7 8]]
arr1Trans : 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [36]:
# 2 3 4
# 0 1 2
arr1 = np.arange(1,25).reshape(2,3,4)
# arr1Trans = np.transpose(arr1,(2,1,0)) # 4 3 2
# arr1Trans = np.transpose(arr1,(2,0,1))
# arr1Trans = np.transpose(arr1,(0,2,1))
arr1Trans = np.transpose(arr1,(1,0,2))
print(f"arr1 : \n {arr1}")
print(f"arr1Trans : \n {arr1Trans}")

arr1 : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
arr1Trans : 
 [[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]


In [9]:
arr1 = np.arange(1,11)
# type(arr1)
arr1

# arr1
# arr2 = np.reshape(arr1,(2,5))
# arr2 = arr1.reshape(2,5)
# print(arr2)

arr3 = arr1.reshape(2,5,order='f')
print(arr3)
# # arr2


[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [25]:
arr1 = np.arange(1,6)
arr1
arr2 = np.resize(arr1,(2,2))
#arr2 = np.resize(arr1,(2,3))
arr2
# arr3 = np.resize([0,1],(8,8))
# arr3

array([[1, 2],
       [3, 4]])

In [17]:
arr1 = np.arange(1,13).reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
# enum = np.nditer(arr1)
# # enum = np.ndenumerate(arr1)
# type(enum)
# print(np.nditer(1,1))
# for i,j in np.ndenumerate(arr1):
#   print(i," - ",j)

# for x,y in enum.nditer([a,b]):
#     print("%d:%d" % (x,y))

# arr2 = arr1.flatten()
#arr1.flat
arr2 = arr1.flatten()
arr2


array([1, 2, 3, 4, 5])

In [ ]:
arr1 = np.array([10,20,30])
arr2 = np.array([40])

print(" a+b ",arr1+arr2 )

 a+b  [50 60 70]


In [ ]:
arr1 = np.array([[10,20],[30,40],[50,60]])
arr2 = np.array([10,20])

print(arr1+arr2 )

[[20 40]
 [40 60]
 [60 80]]


In [ ]:
arr1 = np.array([[10],[20],[30]])
arr2 = np.array([10,20,30])

print(arr1+arr2 )

[[20 30 40]
 [30 40 50]
 [40 50 60]]


In [ ]:
chess = np.zeros((8,8),dtype=int)
chess[1::2,::2] = 1
chess[::2,1::2] = 1
print(chess)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 2 Create a null array of size 10 but the fifth value which is 1
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#4 Create a 5x5 array with random values and find the minimum and maximum values
arr = np.random.random((10,10))
# min, max = arr.min(), arr.max()
# print(min, max)

array([[0.55299344, 0.66133865, 0.92926466, 0.23129587, 0.64715531,
        0.27586226, 0.88561886, 0.69492191, 0.77040822, 0.83887552],
       [0.59542605, 0.25270439, 0.9575267 , 0.07289194, 0.13288565,
        0.75283126, 0.84054667, 0.00113893, 0.73447572, 0.35906656],
       [0.77763753, 0.92948787, 0.72364432, 0.96113996, 0.83736583,
        0.12620878, 0.40371955, 0.08758224, 0.99684976, 0.58643221],
       [0.77511955, 0.19389976, 0.34224117, 0.54718657, 0.53763059,
        0.98846374, 0.22243832, 0.56112354, 0.575047  , 0.70857353],
       [0.35503372, 0.50106155, 0.01195907, 0.33082938, 0.63961185,
        0.91554622, 0.7299596 , 0.98668988, 0.63231087, 0.07171669],
       [0.41140495, 0.98069554, 0.34901602, 0.64477234, 0.91501854,
        0.84065792, 0.69366219, 0.06065558, 0.80400468, 0.36529272],
       [0.67216376, 0.52792007, 0.15212394, 0.05473843, 0.4208355 ,
        0.50965468, 0.04109187, 0.90642967, 0.66877504, 0.43224055],
       [0.69619843, 0.75368503, 0.6107269

In [ ]:
#5 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
arr = np.diag(np.arange(4)+1,k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
# #6 Create a 2d array with 1 on the border and 0 inside
# arr = np.ones((5,5),dtype = int)
# arr[1:-1,1:-1] = 0
# arr


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#8 Create a random array of size 10 and sort it.
arr = np.random.random(10)
arr.sort()
arr

array([0.04198261, 0.15458253, 0.42084028, 0.50400837, 0.70297689,
       0.7637555 , 0.77315495, 0.8076211 , 0.82117141, 0.88289717])

In [ ]:
#9 How to swap two rows of matrix.
arr = np.arange(25).reshape(5,5)
arr[[0,1]] = arr[[1,0]]
arr

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])